package:
  name: aubio
  version: 0.4.3

source:
  git_url: https://github.com/aubio/aubio.git
  #fn: aubio-0.4.2.tar.bz2
  #url: http://aubio.org/pub/aubio-0.4.2.tar.bz2
  #md5: c0f6d8355e92669722501c3a762ba548
  #sha1: aa0d31c58deb92ab03edfc417d903f50f78444d0

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy

test:
  commands:
    - aubioonset --help
    - aubiocut --help
    - aubiopitch --help
  imports:
    - aubio

build:
  number: 1

about:
  home: https://aubio.org/
  license: GPL 3
  summary: "a library for audio labelling"
