#! /usr/bin/python

import unittest

from glob import glob
def list_of_test_files(path):
  return [i.split('.')[0].replace('/','.') for i in glob(path)]

modules_to_test  = []
modules_to_test += list_of_test_files('src/*.py')
modules_to_test += list_of_test_files('src/*/*.py')
modules_to_test += list_of_test_files('examples/aubio*.py')
modules_to_test += list_of_test_files('*.py')

if __name__ == '__main__':
  for module in modules_to_test: 
    if module != 'run_all_tests': # (not actually needed)
      exec('from %s import *' % module)
  unittest.main()
