.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH AUBIONOTES 1 "May  3, 2004"
.\" Please adjust this date whenever revising the man-page.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for man-page-specific macros, see man(7)
.SH NAME
aubionotes \- detects notes in a sound file 
.SH SYNOPSIS
.B aubionotes
.RI [ -i | --input
.RB < soundfilein > 
.RI ]
.RI [ -o | --output 
.RB < soundfileout > 
.RI ]
.RI [ -t | --threshold 
.RB < thres > 
.RI ]
.RI [ -j | --jack ]
.RI [ -v | --verbose ]
.SH DESCRIPTION
This manual page documents briefly the
.B aubionotes
command.
.PP
The library \fBaubio\fP provides a small set of functions to extract events and
objects from audio, from live streams or still files. Onsets are used to label
the beginning of notes, pitches to label their height.

\fBaubionotes\fP is still in an experimental state. Its aim is to segment notes
with onsets, and label them with their detected pitch. When started without an
input file argument (\fI\-i\fP), aubionotes creates a jack input and a midi
output. When an input file is given, it outputs the results on the console.

.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-i, \-\-input filein
Run analysis on this audio file. Most common (uncompressed) formats are 
supported.
.TP
.B \-o, \-\-output fileout
Save results in this file. The file will be created on the model of the input
file. Results are marked by a very short wood-block sample.
.TP
.B \-t, \-\-threshold value
Set the threshold value for the onset peak picking. Typical values are within
\fI0.001\fP and \fI0.900\fP. Default is \fI0.1\fP. The \fBlower\fP the \fBmore
sensible\fP.  Try \fI0.3\fP in case of over-detections.
.TP
.B \-j, \-\-jack
Run in jack mode (default when started without input file) and creates a midi output.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-verbose
Show results on the console.

.SH EXAMPLES
.TP
.I Analyse a file and save the notes times and pitches 

$ aubionotes -v -i myloop.wav 2> myloop.txt

The results are expressed in seconds and midi pitch. 

.TP
.I Start as a jack client

$ aubionotes -t 0.4

Note you will need to have \fIjackd\fP(1) running. Try connecting a midi
instrument to the aubio midi output.

.SH LIMITATIONS
The audio feedback is still limited to playing a wood-block sound.
.SH BUGS
For now the program works only on audio signals sampled at 44.1 kHz. It is also
way too intensive. Hopefully this will be fixed in the next release.
.SH SEE ALSO
The source code is documented using
.IR doxygen (1),
available in the documentation package or at 
.BR http://piem.homeip.net/~piem/aubio/doc/ .
.SH AUTHOR
This manual page was written by Paul Brossier <piem@altern.org>,
for the Debian project (but may be used by others).
