.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH AUBIOONSET 1 "May  3, 2004"
.\" Please adjust this date whenever revising the man-page.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for man-page-specific macros, see man(7)
.SH NAME
aubioonset \- detects onset times in a sound file 
.SH SYNOPSIS
.B aubioonset
.RI [ -i | --input
.RB < soundfilein > 
.RI ]
.RI [ -o | --output 
.RB < soundfileout > 
.RI ]
.RI [ -t | --threshold 
.RB < thres > 
.RI ]
.RI [ -j | --jack ]
.RI [ -v | --verbose ]

.SH DESCRIPTION
This manual page documents briefly the
.B aubioonset
command.
.PP
The \fBaubio\fP library provides a small set of functions to extract events and
objects from audio, from live streams or still files. Onsets are used to label
the beginning of notes.

\fBaubioonset\fP extract onsets from an audio input. It works online or
off-line: live as a jack client, or with an input sound file. When running on a
file, results can be printed to the console using the \fI\-v\fP flag.

.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-i, \-\-input filein
Run analysis on this audio file. Most common (uncompressed) formats are 
supported.
.TP
.B \-o, \-\-output fileout
Save results in this file. The file will be created on the model of the input
file. Results are marked by a very short wood-block sample.
.TP
.B \-t, \-\-threshold value
Set the threshold value for the onset peak picking. Typical values are within
\fI0.001\fP and \fI0.900\fP. Default is \fI0.1\fP. The \fBlower\fP the \fBmore
sensible\fP.  Try \fI0.3\fP in case of over-detections.
.TP
.B \-j, \-\-jack
Run in jack mode (default when started without input file).
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-verbose
Show results on the console.

.SH EXAMPLES
.TP
.I Analyse a file and save the onsets times (in seconds)

$ aubioonset -v -i myloop.wav 2> myloop.txt

One can start a new project in \fIaudacity\fP(1), import myloop.wav as an audio
track, and myloop.txt as a label track. This allows to verify each onset
position, label them with text and select notes, bars and loops.

.TP
.I Start as a jack client

$ aubioonset -t 0.2

Note you will need to have \fIjackd\fP(1) running.

.SH LIMITATIONS
The audio feedback in both case is still limited to playing a wood-block sound.
Midi messages will be sent in the near future.
.SH BUGS
For now the program works only on audio signals sampled at 44.1 kHz.
.SH SEE ALSO
The source code is documented using
.IR doxygen (1),
available in the documentation package or at 
.BR http://piem.homeip.net/~piem/aubio/doc/ .
.SH AUTHOR
This manual page was written by Paul Brossier <piem@altern.org>,
for the Debian project (but may be used by others).
