#! /bin/sh

export CFLAGS=-I/Users/piem/Library/Python/2.7/site-packages/numpy-1.8.0.dev_436a28f_20120710-py2.7-macosx-10.7-x86_64.egg/numpy/core/include/
export LDFLAGS=-L../../build/src/
python setup.py clean build
export PYTHONPATH=./build/lib.macosx-10.6-intel-2.7:$PYTHONPATH
export DYLD_LIBRARY_PATH=../../build/src
./run_all_tests --verbose
