#! /bin/sh

set -e
set -x

export CFLAGS="-I/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy-1.8.0*/numpy/core/include/ -arch i386 -arch x86_64"
export LDFLAGS=-L../../build/src/
python setup.py clean build
export PYTHONPATH=./build/lib.macosx-10.6-intel-2.7:$PYTHONPATH
export DYLD_LIBRARY_PATH=../../build/src
./run_all_tests --verbose
