#! /usr/bin/python

from aubio.bench.node import *

datapath = '/var/www'
respath = '/var/tmp'

def my_print(input,output):
        cmd = "%s %s %s" % ("time sleep 0.3; echo",input,output)
        return runcommand(cmd,debug=0)

act_on_results(mkdir,datapath,respath,filter='d')
act_on_data(my_print,datapath,respath,suffix='.txt')
